"""add evidence table

Revision ID: 89e498322fb2
Revises: 63115db5ebb2
Create Date: 2026-08-09 01:29:10.089012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89e498322fb2'
down_revision: Union[str, Sequence[str], None] = '63115db5ebb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('span_id', sa.String(length=16), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_id', sa.Uuid(), nullable=True),
    sa.Column('collector_run_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_evidence_service'), 'evidence', ['service'], unique=False)
    op.create_index(op.f('ix_evidence_signal'), 'evidence', ['signal'], unique=False)
    op.create_index(op.f('ix_evidence_timestamp'), 'evidence', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_timestamp'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_signal'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_service'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
